---
title: "North Atlantic Swordish MSE"
subtitle: "Example of running an MSE"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Laurence Kell"
output: rmarkdown:::pdf_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{FLife-WKLife}
  %\VignetteEncoding{UTF-8}
bibliography: refs.bib
tags: FLPKG FLR
license: Creative Commons Attribution-ShareAlike 4.0 International
---


```{r knitr_init, echo=FALSE, results="hide"}
library(knitr)
## Global options
opts_chunk$set(cache     =!TRUE,
               echo      =TRUE,
               eval      =TRUE,
               prompt    =FALSE,
               comment   =NA,
               message   =FALSE,
               warning   =FALSE,
               tidy      =FALSE,
               fig.height=6,
               fig.width =8)

iFig=0
```


```{r, pkgs, message=FALSE}
library(ggplotFL)
library(plyr)
library(reshape)
library(FLBRP)
library(FLife)
```

```{r, theme, echo=FALSE}
theme_set(theme_bw())
options(digits=3)
```

**Figure `r iFig=iFig+1; iFig`** Simulate a stock with increasing F

## Software Versions

* `r version$version.string`
* FLCore: `r packageVersion('FLCore')`
* FLPKG: `r # packageVersion('FLPKG')`
* **Compiled**: `r date()`
* **Git Hash**: `r system("git log --pretty=format:'%h' -n 1", intern=TRUE)`

## Author information

**Laurence KELL**. laurie@seaplusplus.co.uk

## Acknowledgements


# References {#References}


